title: Vincent Tian
logo: /assets/img/headshot.png
description: Hey there! I'm Vincent, originally from Perth, Australia. Currently, I'm pursuing my Master’s in Business Analytics @ MIT. Prior to MIT, I worked for ~3 years as a data scientist across health & government sectors and in retail product analytics. I have also interned in the epidemiology and mining sectors. Would love to connect! 😊
show_downloads: true
theme: jekyll-theme-minimal

