title: Vincent Tian
logo: /assets/img/headshot.png
description: Hi! I am Vincent 😊 I'm a current Master\'s of Business Analytics student at MIT. Before coming to MIT I worked for ~3 years as a data scientist in the government and product analytics industries.
show_downloads: true
theme: jekyll-theme-minimal

